<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Notilify</PackageId>
    <Version>0.1.0</Version>
    <Description>Official .NET SDK for the Notilify transactional SMS API</Description>
    <Authors>Notilify</Authors>
    <Company>Notilify</Company>
    <PackageProjectUrl>https://notilify.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/notilify/notilify-sdks.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>notilify;sms;transactional-sms</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
